# Generated by Django 5.2.8 on 2025-12-31 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('stores', '0003_rename_stores_partn_3cddbe_idx_stores_partner_a7aed6_idx_and_more'),
        ('users', '0003_create_demo_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreAdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGNED', 'Assigned to Store'), ('MOVED', 'Moved to Different Store'), ('REMOVED', 'Removed from Store'), ('ROLE_CHANGED', 'Role Changed')], max_length=20)),
                ('old_role', models.CharField(blank=True, max_length=20, null=True)),
                ('new_role', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'store_admin_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='barcode_counter',
            field=models.PositiveIntegerField(default=1, help_text='Counter for sequential barcode generation'),
        ),
        migrations.AddField(
            model_name='partner',
            name='barcode_format',
            field=models.CharField(choices=[('EAN13', 'EAN-13'), ('CODE128', 'Code 128'), ('CUSTOM', 'Custom')], default='EAN13', help_text='Barcode format for product barcodes', max_length=20),
        ),
        migrations.AddField(
            model_name='partner',
            name='barcode_prefix',
            field=models.CharField(blank=True, help_text='Optional prefix for custom barcode generation', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='assigned_store',
            field=models.ForeignKey(blank=True, help_text='Store assigned to this user (required for STORE_ADMIN and CASHIER roles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_users', to='stores.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='sms_phone',
            field=models.CharField(blank=True, help_text='Phone number for SMS notifications', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STORE_ADMIN', 'Store Admin'), ('INVENTORY_STAFF', 'Inventory Staff'), ('CASHIER', 'Cashier'), ('VIEWER', 'Viewer')], default='VIEWER', help_text='User role for permission management', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['assigned_store'], name='users_assigne_affb0a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['partner', 'role'], name='users_partner_54805a_idx'),
        ),
        migrations.AddField(
            model_name='storeadminauditlog',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='storeadminauditlog',
            name='new_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_new', to='stores.store'),
        ),
        migrations.AddField(
            model_name='storeadminauditlog',
            name='old_store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs_old', to='stores.store'),
        ),
        migrations.AddField(
            model_name='storeadminauditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_audit_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='storeadminauditlog',
            index=models.Index(fields=['user', 'created_at'], name='store_admin_user_id_7dc293_idx'),
        ),
    ]
