# Generated by Django 5.1.3 on 2025-11-25 16:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('IN', 'Stock In'), ('OUT', 'Stock Out'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('reason', models.CharField(choices=[('PURCHASE', 'Purchase Order Receipt'), ('SALE', 'Sale'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('RECONCILIATION', 'Stock Reconciliation'), ('RETURN', 'Return'), ('MANUAL', 'Manual Adjustment')], max_length=30)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_before', models.IntegerField()),
                ('quantity_after', models.IntegerField()),
                ('reference_number', models.CharField(blank=True, help_text='PO number, Sale number, or other reference', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
