# Generated by Django 5.1.3 on 2025-11-28 07:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('stock', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total cost (quantity × unit_cost)', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost per unit at time of transaction (for IN transactions)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.CreateModel(
            name='ProductCostHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('new_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reason', models.CharField(help_text='Reason for cost change', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_changes', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_history', to='inventory.product')),
                ('stock_transaction', models.ForeignKey(blank=True, help_text='The stock transaction that triggered this cost change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cost_changes', to='stock.stocktransaction')),
            ],
            options={
                'verbose_name_plural': 'Product cost histories',
                'db_table': 'product_cost_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product'], name='product_cos_product_08b8ed_idx'), models.Index(fields=['-created_at'], name='product_cos_created_54cda4_idx')],
            },
        ),
    ]
