# Generated by Django 5.2.8 on 2025-11-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_add_partner_field'),
        ('stock', '0003_stocktransaction_total_cost_and_more'),
        ('users', '0002_add_partner_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this stock transaction belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_transactions', to='users.partner'),
        ),
        migrations.AddIndex(
            model_name='stocktransaction',
            index=models.Index(fields=['partner'], name='stock_trans_partner_06ac07_idx'),
        ),
    ]
