# Generated by Django 5.2.8 on 2025-12-25 03:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_assign_demo_partner'),
        ('stock', '0005_assign_demo_partner'),
        ('users', '0003_create_demo_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='productcosthistory',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this cost history belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_cost_histories', to='users.partner'),
        ),
        migrations.AddIndex(
            model_name='productcosthistory',
            index=models.Index(fields=['partner'], name='product_cos_partner_1bb65a_idx'),
        ),
    ]
