# Generated by Django 5.2.8 on 2025-12-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_add_store_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productcosthistory',
            new_name='product_cos_store_i_3901f2_idx',
            old_name='product_cos_store_i_3f4f97_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktransaction',
            new_name='stock_trans_store_i_f8877a_idx',
            old_name='stock_trans_store_i_6c7cd2_idx',
        ),
    ]
