# Generated by Django 5.2.8 on 2025-11-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_remove_expense_approved_by_remove_expense_status'),
        ('users', '0002_add_partner_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this expense belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='users.partner'),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this expense category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='users.partner'),
        ),
        migrations.AlterField(
            model_name='expensecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='expensecategory',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='unique_expense_category_per_partner'),
        ),
    ]
