# Generated by Django 5.2.8 on 2025-12-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_add_store_fields'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='expensecategory',
            name='unique_expense_category_per_partner',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='expenses_store_i_29d9a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='expensecategory',
            name='expense_c_stor_i_072968_idx',
        ),
    ]
