# Generated by Django 5.2.8 on 2025-11-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_wholesale_price'),
        ('users', '0002_add_partner_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this category belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='users.partner'),
        ),
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this product belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.partner'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this purchase order belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='users.partner'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this supplier belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='users.partner'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(help_text='Stock Keeping Unit / Part Number', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='po_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['partner'], name='products_partner_bbe5ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='unique_category_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('partner', 'sku'), name='unique_sku_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('barcode__isnull', False)), fields=('partner', 'barcode'), name='unique_barcode_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='purchaseorder',
            constraint=models.UniqueConstraint(fields=('partner', 'po_number'), name='unique_po_number_per_partner'),
        ),
        migrations.AddConstraint(
            model_name='supplier',
            constraint=models.UniqueConstraint(fields=('partner', 'name'), name='unique_supplier_per_partner'),
        ),
    ]
