# Generated by Django 5.2.8 on 2025-12-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_assign_demo_partner'),
        ('stores', '0003_rename_stores_partn_3cddbe_idx_stores_partner_a7aed6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available_stores',
            field=models.ManyToManyField(blank=True, help_text='Stores where this product is available. Empty means available in all partner stores.', related_name='available_products', to='stores.store'),
        ),
    ]
