# Generated by Django 5.2.8 on 2026-01-01 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_product_available_stores'),
        ('stores', '0003_rename_stores_partn_3cddbe_idx_stores_partner_a7aed6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.IntegerField(default=0, help_text='Current available stock quantity at this store', validators=[django.core.validators.MinValueValidator(0)])),
                ('minimum_stock_level', models.IntegerField(default=10, help_text='Alert when stock falls below this level for this store', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(help_text='Product being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='store_inventories', to='inventory.product')),
                ('store', models.ForeignKey(help_text='Store where this inventory is located', on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='stores.store')),
            ],
            options={
                'verbose_name_plural': 'Store Inventories',
                'db_table': 'store_inventories',
                'ordering': ['store', 'product'],
                'indexes': [models.Index(fields=['product'], name='store_inven_product_e6556c_idx'), models.Index(fields=['store'], name='store_inven_store_i_77edbe_idx'), models.Index(fields=['current_stock'], name='store_inven_current_d8cabf_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'store'), name='unique_product_per_store')],
            },
        ),
    ]
