# Generated by Django 5.2.8 on 2026-01-01 02:22

from django.db import migrations


def migrate_product_stock_to_store_inventory(apps, schema_editor):
    """
    Migrate existing product stock to StoreInventory.
    For each product with stock > 0, create StoreInventory records for all stores
    where the product is available.
    """
    Product = apps.get_model('inventory', 'Product')
    StoreInventory = apps.get_model('inventory', 'StoreInventory')
    Store = apps.get_model('stores', 'Store')
    
    for product in Product.objects.all():
        # Skip products with no stock
        if product.current_stock == 0:
            continue
            
        # Get stores where this product is available
        available_stores = list(product.available_stores.all())
        
        # If no stores specified, product is available at all partner stores
        if not available_stores:
            available_stores = list(Store.objects.filter(partner=product.partner))
        
        # If still no stores (shouldn't happen), skip
        if not available_stores:
            continue
        
        # Distribute stock evenly across available stores (or put all in first store)
        # For simplicity, we'll put all stock in the first available store
        first_store = available_stores[0]
        
        # Create StoreInventory record
        StoreInventory.objects.create(
            product=product,
            store=first_store,
            current_stock=product.current_stock,
            minimum_stock_level=product.minimum_stock_level
        )
        
        # Create zero-stock records for other stores
        for store in available_stores[1:]:
            StoreInventory.objects.create(
                product=product,
                store=store,
                current_stock=0,
                minimum_stock_level=product.minimum_stock_level
            )


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: aggregate StoreInventory back to Product.current_stock
    """
    Product = apps.get_model('inventory', 'Product')
    StoreInventory = apps.get_model('inventory', 'StoreInventory')
    
    for product in Product.objects.all():
        # Sum up stock from all stores
        total_stock = sum(
            inv.current_stock 
            for inv in StoreInventory.objects.filter(product=product)
        )
        product.current_stock = total_stock
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_add_store_inventory'),
        ('stores', '0001_initial'),  # Make sure Store model is available
    ]

    operations = [
        migrations.RunPython(
            migrate_product_stock_to_store_inventory,
            reverse_migration
        ),
    ]
