# Generated by Django 5.2.8 on 2026-01-01 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_migrate_stock_to_store_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='product',
            name='minimum_stock_level',
        ),
    ]
