# Generated by Django 5.2.8 on 2025-12-31 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_create_default_stores'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='store',
            new_name='stores_partner_a7aed6_idx',
            old_name='stores_partn_3cddbe_idx',
        ),
        migrations.RenameIndex(
            model_name='store',
            new_name='stores_is_acti_89b637_idx',
            old_name='stores_is_ac_b6fc15_idx',
        ),
        migrations.AddField(
            model_name='store',
            name='auto_print_receipt',
            field=models.BooleanField(default=False, help_text='Automatically print receipt after sale completion'),
        ),
        migrations.AddField(
            model_name='store',
            name='printer_name',
            field=models.CharField(blank=True, help_text='Name of the printer to use for receipts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='receipt_template',
            field=models.TextField(default='\n=====================================\n           {{store_name}}\n=====================================\n{{store_address}}\nTel: {{store_phone}}\n\nReceipt #: {{sale_number}}\nDate: {{date}}\nCashier: {{cashier}}\n-------------------------------------\nITEMS:\n{{items}}\n-------------------------------------\nSubtotal:          {{subtotal}}\nDiscount:          {{discount}}\n-------------------------------------\nTOTAL:             {{total}}\n-------------------------------------\nPayment: {{payment_method}}\n=====================================\n     Thank you for your purchase!\n=====================================\n', help_text='Receipt template with placeholders (editable via Django admin)'),
        ),
    ]
