# Generated by Django 5.2.8 on 2025-12-31 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('SALES_CSV', 'Sales CSV'), ('SALES_EXCEL', 'Sales Excel'), ('SALES_PDF', 'Sales PDF'), ('PRODUCTS_CSV', 'Products CSV'), ('PRODUCTS_EXCEL', 'Products Excel'), ('STOCK_CSV', 'Stock CSV'), ('STOCK_EXCEL', 'Stock Excel')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('filters', models.JSONField(blank=True, help_text='Filters applied to the export', null=True)),
                ('file_path', models.CharField(blank=True, help_text='Path to the generated file', max_length=500, null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if export failed', null=True)),
                ('progress', models.IntegerField(default=0, help_text='Progress percentage (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='export_jobs_user_id_d4ca06_idx'), models.Index(fields=['created_at'], name='export_jobs_created_af4995_idx')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('STORE_ADMIN_TRANSFER', 'Store Admin Transfer'), ('LOW_STOCK_ALERT', 'Low Stock Alert'), ('OUT_OF_STOCK_ALERT', 'Out of Stock Alert'), ('EXPORT_COMPLETE', 'Export Complete'), ('STORE_DEACTIVATED', 'Store Deactivated'), ('STORE_ACTIVATED', 'Store Activated'), ('PASSWORD_RESET', 'Password Reset'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('data', models.JSONField(blank=True, help_text='Optional JSON data for notification context', null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='notificatio_user_id_c4e471_idx'), models.Index(fields=['user', 'type'], name='notificatio_user_id_6b5847_idx')],
            },
        ),
    ]
