# Generated by Django 5.2.8 on 2025-11-28 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='is_wholesale',
            field=models.BooleanField(default=False, help_text='Whether this sale used wholesale pricing'),
        ),
    ]
