# Generated by Django 5.2.8 on 2025-11-30 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_is_wholesale'),
        ('users', '0002_add_partner_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='partner',
            field=models.ForeignKey(blank=True, help_text='Partner/tenant this sale belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='users.partner'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['partner'], name='sales_partner_f82770_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(fields=('partner', 'sale_number'), name='unique_sale_number_per_partner'),
        ),
    ]
