# Generated by Django 5.2.8 on 2025-12-31 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_add_store_to_sales'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sale',
            new_name='sales_store_i_98cf2c_idx',
            old_name='sales_store_idx',
        ),
    ]
